name: cellular_automata_dev

channels:
  - conda-forge

dependencies:
  - python>=3.9,<3.12
  - pip=22.3.1
  - setuptools=66.1.1

  - pip:
      - -e ".[dev]"                      # Install current repo as editable package
